name: Doug Shamoo
description: Blogging about code and stuff
meta_description: "Doug Shamoo, Blogging about code and stuff"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://dougshamoo.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://dougshamoo.github.io'
author:         'Doug Shamoo'
