name: Doug Shamoo
description: Blogging about code and stuff
meta_description: "Doug Shamoo, Blogging about code and stuff"

markdown: redcarpet
highlighter: pygments
logo: assets/images/profile.png
paginate: 15
baseurl: /
domain_name: 'http://dougshamoo.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'www.dougshamoo.com'
author:         'Doug Shamoo'
